uac: fix unknown type name
introduced at b6e264c9780fc0432e6e746f473024e41bc1126b

> uac_send.c: In function 'uac_send_tm_callback':
> uac_send.c:741:16: error: unknown type name 'authenticate_body_t'
>   741 |         static authenticate_body_t auth;
>       |                ^~~~~~~~~~~~~~~~~~~
> uac_send.c:781:49: warning: passing argument 2 of 'parse_authenticate_body' from incompatible pointer type [-Wincompatible-pointer-types]
>   781 |         if (parse_authenticate_body(&hdr->body, &auth)<0)
>       |                                                 ^~~~~
>       |                                                 |
>       |                                                 int *
> In file included from uac_send.c:42:
> auth_hdr.h:30:67: note: expected 'struct authenticate_body *' but argument is of type 'int *'
>    30 | int parse_authenticate_body( str *body, struct authenticate_body *auth);
>       |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
> uac_send.c:788:27: error: request for member 'realm' in something not a structure or union
>   788 |         cred.realm  = auth.realm;
>       |                           ^
> uac_send.c:795:56: warning: passing argument 4 of 'do_uac_auth' from incompatible pointer type [-Wincompatible-pointer-types]
>   795 |         do_uac_auth(&tp->s_method, &tp->s_ruri, &cred, &auth, response);
>       |                                                        ^~~~~
>       |                                                        |
>       |                                                        int *
> In file included from uac_send.c:41:
> auth.h:77:43: note: expected 'struct authenticate_body *' but argument is of type 'int *'
>    77 |                 struct authenticate_body *auth,
>       |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
> uac_send.c:797:49: warning: passing argument 4 of 'build_authorization_hdr' from incompatible pointer type [-Wincompatible-pointer-types]
>   797 |                                                 &auth, response);
>       |                                                 ^~~~~
>       |                                                 |
>       |                                                 int *
> In file included from uac_send.c:42:
> auth_hdr.h:33:71: note: expected 'struct authenticate_body *' but argument is of type 'int *'
>    33 |                 struct uac_credential *crd, struct authenticate_body *auth,
>       |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
> make[2]: *** [../../Makefile.rules:100: uac_send.o] Error 1