ldap(k): fix ldapsearch with empty filter
  * fix ldapsearch with empty filter
  * When in routing script ldapsearch() is executed on LDAP query URL without
    the ‘filter’ section, request forming fails:
    ERROR: ldap [ldap_api_fn.c:193]: vsnprintf failed
  * Workaround for administrators can be filling filter section with
    ‘(objectclass=*)’, what is anyway substituted by ldap library to request
    in case filter parameter set to NULL.
 * Please notice that va_end() call is missing in original code.
 * Patch FS#23 from andrey dot utkin at wildix dot com
(cherry picked from commit 73655cc83851f1f406ce23b8d6130632d731ef2d)