cfgt: fix implicit declaration of 'strcasestr'
> cfgt_int.c: In function 'cfgt_msgout':
> cfgt_int.c:863:21: warning: implicit declaration of function 'strcasestr'; did you mean 'strcasecmp'? [-Wimplicit-function-declaration]
>  863 |  if(buf->len > 7 && strcasestr(buf->s, "OPTIONS")) {
>      |                     ^~~~~~~~~~
>      |                     strcasecmp

(cherry picked from commit 361542a953ceaab1894f790e21eecf74008b749a)