core parser: fix after 316ea8925edd0c401c121e9dc0f21dde3a2c6598
> Error: core/parser/msg_parser.c:423:9: error: call to undeclared function 'parse_from_header'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>  423 |                                         if(parse_from_header(msg) < 0) {
>       |                                            ^
> core/parser/msg_parser.c:423:9: note: did you mean 'parse_to_header'?
> core/parser/parse_to.h:48:5: note: 'parse_to_header' declared here
>    48 | int parse_to_header(struct sip_msg *const msg);
>       |     ^
> 1 error generated.

(cherry picked from commit d8715c16fb79365a26fb75990565be4fea701ae6)