snmpstats: fix build, update memory field
> CC (gcc) [M snmpstats.so]               kamailioServer.o
> kamailioServer.c: In function 'handle_kamailioSrvFreeMemory':
> kamailioServer.c:193:37: error: 'struct mem_info' has no member named 'free'
>   193 |  int freememory = (int)_stats_shm_mi.free;
>       |                                     ^
> make[2]: *** [../../Makefile.rules:100: kamailioServer.o] Error 1
> make[1]: *** [Makefile:511: modules] Error 1

changes introduced at fb8727b3e1b9fc4f4278809ef9cdea93e96ae77a