core: fix compilation error
- UINT32_MAX is defined in <stdint.h>

> CC (clang) [kamailio]           core/tcp_main.o
> core/tcp_main.c:1134:16: error: use of undeclared identifier 'UINT32_MAX'
>                         if (port == UINT32_MAX || port == 0 || port >= (1 << 16)) {
>                                     ^