carrierroute: rename boolean type conflicting with clang sdtbool
In file included from carrierroute.c:51:
./cr_db.h:92:2: error: expected identifier
        false = 0,
        ^
/usr/lib/clang/9.1.0/include/stdbool.h:33:15: note: expanded from
      macro 'false'
 #define false 0

(cherry picked from commit 0a14914fc1f98c18b9b75f66fe2e71f15147c9bf)
(cherry picked from commit 9aee0374e1db8733a220d37fbc53517353aee4dd)