core: Don't bind to IPv6 addresses if auto_bind_ipv6 is disabled
With the following listen statement:
   listen=udp:eth0:5060
Kamailio would try to bind to the IPv6 address(es) on that interface and fail with:

ERROR: <core> [udp_server.c:369]: udp_init(): might be caused by using a link local address, try site local or global
(cherry picked from commit 8102ca5f67de979a3597a97f96a05c99d13fb29d)