db_unixodbc: fix incompatible-pointer-types warning
> dbase.c: In function 'db_unixodbc_close_impl':
> dbase.c:261:32: error: passing argument 2 of 'db_do_close' from incompatible pointer type [-Wincompatible-pointer-types]
>  261 |         return db_do_close(_h, db_unixodbc_free_connection);
>      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>      |                                |
>      |                                void (*)(struct my_con *)
> In file included from val.h:34,
>                  from dbase.c:33:
> ../../lib/srdb1/db.h:495:40: note: expected 'void (*)(struct pool_con *)' but argument is of type 'void (*)(struct my_con *)'
>   495 | void db_do_close(db1_con_t *_h, void (*free_connection)(struct pool_con *));
>       |                                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> make[2]: *** [../../Makefile.rules:101: dbase.o] Error 1

related #4064

(cherry picked from commit 7f24bc09863220b4c14e2046708c10ff0891c038)