auth_identity: switched to use pointer of X509_STORE_CTX
- starting with libssl 1.1.0 the size of X509_STORE_CTX is not known at
  compile time, throwing error:

error: storage size of 'ca_ctx' isn't known
   X509_STORE_CTX ca_ctx;

- reported by Victor Seva, GH #685

(cherry picked from commit 46f0f1c0f492c45c1b1bbcfd4a0cc63eb56480ea)