xmlrpc: remove redeclaration of snprintf and vsnprintf
compilation was failling with clang:

> CC (clang) [M xmlrpc.so]		xmlrpc.o
> xmlrpc.c:152:5: error: expected parameter declarator
> int snprintf(char *str, size_t size, const char *format, ...);
>     ^
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:69:39: note: expanded from macro 'snprintf'
>   __builtin___snprintf_chk (str, len, __USE_FORTIFY_LEVEL - 1, __bos (str), \
>                                       ^
> /usr/include/features.h:329:31: note: expanded from macro '__USE_FORTIFY_LEVEL'
> #  define __USE_FORTIFY_LEVEL 2
>                               ^
> xmlrpc.c:152:5: error: expected ')'
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:69:39: note: expanded from macro 'snprintf'
>   __builtin___snprintf_chk (str, len, __USE_FORTIFY_LEVEL - 1, __bos (str), \
>                                       ^
> /usr/include/features.h:329:31: note: expanded from macro '__USE_FORTIFY_LEVEL'
> #  define __USE_FORTIFY_LEVEL 2
>                               ^
> xmlrpc.c:152:5: note: to match this '('
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:69:28: note: expanded from macro 'snprintf'
>   __builtin___snprintf_chk (str, len, __USE_FORTIFY_LEVEL - 1, __bos (str), \
>                            ^
> xmlrpc.c:152:5: error: conflicting types for '__builtin___snprintf_chk'
> int snprintf(char *str, size_t size, const char *format, ...);
>     ^
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:69:3: note: expanded from macro 'snprintf'
>   __builtin___snprintf_chk (str, len, __USE_FORTIFY_LEVEL - 1, __bos (str), \
>   ^
> xmlrpc.c:152:5: note: '__builtin___snprintf_chk' is a builtin with type 'int (char *, unsigned long, int, unsigned long, const char *, ...)'
> /usr/include/x86_64-linux-gnu/bits/stdio2.h:69:3: note: expanded from macro 'snprintf'
>   __builtin___snprintf_chk (str, len, __USE_FORTIFY_LEVEL - 1, __bos (str), \
>   ^
> 3 errors generated.

(cherry picked from commit 358de10a94bef4df6b1811ac8e88ea4e7919542c)