ndb_redis: set message level to debug on exec
* logging error makes no sense here since there's going
  to be a reconnection afterwards

> ERROR: ndb_redis [redis_client.c:903]: redisc_exec_argv(): Redis error: Server closed the connection

(cherry picked from commit a9c331d70dbed6827874aa99296203ac5a9d5c7b)