utils/kamctl: fix handling of Exceptions
> Traceback (most recent call last):
>   File "/usr/lib/x86_64-linux-gnu/kamailio/kamctl/dbtextdb/dbtextdb.py", line 1239, in <module>
>     main(sys.argv)
>   File "/usr/lib/x86_64-linux-gnu/kamailio/kamctl/dbtextdb/dbtextdb.py", line 1233, in main
>     except (Error, e):
> NameError: name 'e' is not defined

(cherry picked from commit 1aca79c43cb8dbd920c1eb81c0c30cf89f0985b9)
(cherry picked from commit 5f6f4331811e654e75b49263f8fb823bea9874a3)