Explicitly cast void* to char*
When compiling a custom module, including `shm_mem.h` caused the
following compilation error:

In file included from ../../core/mem/shm_mem.h:32,
                 from custom_code.cpp:40:
../../core/parser/../ut.h: In function ‘char* shm_char_dup(const char*)’:
../../core/mem/shm.h:67:49: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
   67 | # define shm_malloc(s)         _shm_root.xmalloc(_shm_root.mem_block, (s))
      |                                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |
      |                                                 void*
../../core/parser/../ut.h:811:9: note: in expansion of macro ‘shm_malloc’
  811 |  rval = shm_malloc(len);
      |         ^~~~~~~~~~

gcc version: `gcc (Debian 9.2.1-22) 9.2.1 20200104`